---
- name: Converge
  hosts: all
  become: true
  vars:
    vaultwarden_version: "1.35.1-alpine"
    vaultwarden_data_path: "/opt/services/vaultwarden"
    domain_vaultwarden: "vault.ci-test.local"
    vault_vaultwarden_admin_token: "TestToken123456789"
  roles:
    - role: vaultwarden
