---
- name: Restart monit
  ansible.builtin.service:
    name: monit
    state: restarted
  when: ansible_virtualization_type != "docker"

- name: Reload monit
  ansible.builtin.command:
    cmd: monit reload
  changed_when: true
