---
- name: Prepare - Prerequisites for alloy
  hosts: all
  become: true
  tasks:
    - name: Mettre Ã  jour le cache apt
      ansible.builtin.apt:
        update_cache: true
    - name: Installer curl et gnupg
      ansible.builtin.apt:
        name:
          - curl
          - gnupg
          - apt-transport-https
        state: present
