---
- name: Restart systemd-journald
  ansible.builtin.service:
    name: systemd-journald
    state: restarted
  when: ansible_virtualization_type != "docker"

- name: Restart docker
  ansible.builtin.service:
    name: docker
    state: restarted
  when: ansible_virtualization_type != "docker"

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
