---
- name: Verify
  hosts: all
  become: true
  tasks:
    - name: Vérifier le conteneur Uptime Kuma
      ansible.builtin.command:
        cmd: docker inspect uptime-kuma --format "{{ '{{' }}.State.Running{{ '}}' }}"
      register: uptime_kuma_check
      changed_when: false

    - name: Valider Uptime Kuma
      ansible.builtin.assert:
        that:
          - "'true' in uptime_kuma_check.stdout"

    - name: Vérifier le script de configuration
      ansible.builtin.stat:
        path: /opt/services/uptime-kuma/setup/configure-monitors.py
      register: uptime_kuma_script_check

    - name: Valider le script de configuration
      ansible.builtin.assert:
        that:
          - uptime_kuma_script_check.stat.exists
          - uptime_kuma_script_check.stat.mode == '0700'

    - name: Vérifier le fichier requirements
      ansible.builtin.stat:
        path: /opt/services/uptime-kuma/setup/requirements-setup.txt
      register: uptime_kuma_requirements_check

    - name: Valider le fichier requirements
      ansible.builtin.assert:
        that:
          - uptime_kuma_requirements_check.stat.exists
