---
- name: Verify
  hosts: all
  become: true
  tasks:
    - name: VÃ©rifier le conteneur Uptime Kuma
      ansible.builtin.command:
        cmd: docker inspect uptime-kuma --format "{{ '{{' }}.State.Running{{ '}}' }}"
      register: uptime_kuma_check
      changed_when: false

    - name: Valider Uptime Kuma
      ansible.builtin.assert:
        that:
          - "'true' in uptime_kuma_check.stdout"
