---
- name: Converge
  hosts: all
  become: true
  vars:
    headscale_version: "0.26.0"
    headscale_data_path: "/opt/services/headscale"
    domain_headscale: "hs.ci-test.local"
  roles:
    - role: headscale
