---
- name: Converge
  hosts: all
  become: true
  vars:
    headscale_version: "0.26.0"
    headscale_data_path: "/opt/services/headscale"
    domain_headscale: "hs.ci-test.local"
    headscale_base_domain: "vpn.ci-test.local"
    server_ip: "127.0.0.1"
    server_tailscale_ip: "100.64.0.1"
    domain_headplane: "seko.ci-test.local"
    domain_vaultwarden: "vault.ci-test.local"
    domain_portainer: "pao.ci-test.local"
    domain_zerobyte: "buku.ci-test.local"
    domain_uptime_kuma: "status.ci-test.local"
  roles:
    - role: headscale
