$ANSIBLE_VAULT;1.1;AES256
63623161656366626532383734626663623761656361353265613235613630653766333661396232
3964626530373833323738653931333266643934356136340a353437373138346463363062613263
61396434386335326466336166343966333261306535323032383731643430646163633363356236
3362633765383732610a386132393261343038663438656437636539396231303733383539333932
61666266343061333365326436303933316466356238643363373333373437373933656136663965
65643636633635393738626264393262356535323231613166653730333066376132613531666537
32323837363939306232366632386233396131353037313131343538356664663131666662366164
63336135373830323065666365653465396533656532396538316230636137663661633030363734
37626234663235366238633562626362303138313737306639306639353366373937636566393133
31353139366137303531633139376239373939336364346434383263343733653863616163633739
64633464633763326331623361336661356537333636616264306262316364666634663465653737
62333134363237373865613437363033373666373334616634363139316331646538333333663439
65646333373531636430356231303332346636363763326135623563393935376136656130396364
64343662326238353361613138393430343566663037353265316566313265346565383236376239
33323132343761373936633535623130363265653663356466356331666162633332363064616435
31613761656534333339653134373037373561326338626133306565373762303135376539336663
33646361613265356365346431626535393064663437616235666535346563383563376538636263
30303836643462626266323664316331393236623633393234613231366537646362626161323234
62636262643832336138626364653662306664326238353635396662663634666339323135613439
33383635653866383962623338666437343161623036326233303134366332356565633261373665
35646434623538306566313464343435386233393636306437343366316632653766356132346538
61613432623535393533343566356662306561623433303335373438373665353963393236326232
64313564316332383632613237373930643139633339323635613661356631333438636263636333
62633861616136613531663430633464636635626636663934613162353264366139633430666262
38313236616463643864613032326663313433663561626563316230326337353135363434323035
39366332303562633466366637336230313538393261353634386230306463313663643632646635
61356165656566326162323163333264643865646135663534633135363830393932326436623135
61613137383861626462393934353138353731643164666236636237323136343563396632613630
62383563333532626166353037643439333630336634616533313535633866346566326437643839
35383531333831656337316362373431666532346337636230383661386363323366663865366231
61323962303531393765643163386361383963646466363862313633343039393062656663316535
33643235656162663839
