---
- name: Converge
  hosts: all
  become: true
  vars:
    telegram_bot_server_name: "ci-test-01"
    telegram_bot_path: "/opt/services/telegram-bot"
    base_deploy_path: "/opt/services"
    vault_telegram_bot_token: "123456:ABC-DEF-test-token"
    vault_telegram_chat_id: "123456789"
    domain_headscale: "hs.ci-test.local"
    domain_headplane: "hp.ci-test.local"
    domain_vaultwarden: "vault.ci-test.local"
    domain_portainer: "portainer.ci-test.local"
    domain_zerobyte: "backup.ci-test.local"
    domain_uptime_kuma: "status.ci-test.local"
    ssh_custom_port: 804
  roles:
    - role: telegram_bot
