---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: telegram-bot-debian12
    image: trfore/docker-debian12-systemd
    pre_build_image: true
    privileged: true
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../../../roles"
verifier:
  name: ansible
