---
- name: Créer le répertoire Vaultwarden
  ansible.builtin.file:
    path: "{{ vaultwarden_data_path }}"
    state: directory
    mode: "0755"

- name: Déployer le docker-compose Vaultwarden
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ vaultwarden_data_path }}/docker-compose.yml"
    mode: "0644"

- name: Démarrer Vaultwarden
  community.docker.docker_compose_v2:
    project_src: "{{ vaultwarden_data_path }}"
    state: present
