---
- name: Créer le répertoire Portainer
  ansible.builtin.file:
    path: "{{ portainer_data_path }}"
    state: directory
    mode: "0755"

- name: Déployer le docker-compose Portainer
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ portainer_data_path }}/docker-compose.yml"
    mode: "0644"

- name: Démarrer Portainer
  community.docker.docker_compose_v2:
    project_src: "{{ portainer_data_path }}"
    state: present
