---
- name: Converge
  hosts: all
  become: true
  vars:
    zerobyte_version: "v0.25"
    zerobyte_data_path: "/opt/services/zerobyte"
    vault_zerobyte_app_secret: "a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2"
  roles:
    - role: zerobyte
