---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: common-debian12
    image: geerlingguy/docker-debian12-ansible
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../../../roles"
verifier:
  name: ansible
