---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: caddy-debian12
    image: geerlingguy/docker-debian12-ansible
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../../../roles"
verifier:
  name: ansible
