---
- name: Converge
  hosts: all
  become: true
  vars:
    headplane_version: "latest"
    headplane_data_path: "/opt/services/headplane"
    domain_headplane: "nga.ci-test.local"
    domain_headscale: "hs.ci-test.local"
    vault_headplane_cookie_secret: "a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6"
  roles:
    - role: headplane
